Task 3
Reallife/go-learning pull request #4
Opened 2020-11-25 03:28 UTC by Reallife

2020-11-25 06:06 UTC, Reallife commented on task-3/pkg/processor/processor.go
> +	for idx, word := range words {
`TODO`
Слова, которые тут пропускаем не должны вообще попадать в `map`. Нужно реализовать удаление из хранилища

2020-11-25 06:16 UTC, Reallife commented on task-3/main.go
> +	file, err := os.Open(fileName)
`TODO`
Избавиться от хардкода имени файла (флаги, читать из `stdin`)

2020-11-25 06:30 UTC, Reallife commented on task-3/pkg/processor/processor.go
> +func NewFileProcessor(file io.Reader, storage storage.Storage) Processor {
```suggestion
func NewFileProcessor(file io.Reader, storage storage.Storage) *textProcessor {
```

2020-11-25 06:31 UTC, Reallife commented on task-3/pkg/storage/map.go
> +func NewSortedMap() Storage {
```suggestion
func NewSortedMap() *sortedMap {
```

2020-11-25 09:23 UTC, korjavin requested changes
Я вижу ты уже пометил комментами

+ найти блокер производительности

2020-11-26 23:46 UTC, Reallife commented on task-3/pkg/processor/processor.go
> +	for idx, word := range words {
Done

2020-11-26 23:46 UTC, Reallife commented on task-3/main.go
> +	file, err := os.Open(fileName)
Done

2020-11-30 05:27 UTC, korjavin approved these changes

2020-11-30 19:06 UTC, eldario commented
![image](https://user-images.githubusercontent.com/6119929/100652576-f1b94b80-3368-11eb-9c21-2bbc2c804b5c.png)

[Diff](https://www.diffchecker.com/ZP3u4npm)

2020-12-01 10:26 UTC, merged